### PR TITLE
Create Faris_Nyannyan.json

### PR DESCRIPTION
**Pull request by SaulMiquilena**
Add Faris Nyannyan waifu to list. Uh Oh 17 years old yikes!

### CODE REVIEW

**Comment by yourWaifu** [comment]
can you put the year the show takes place in the notes, I might add a new parameter for the year the show takes place in

**Comment by yourWaifu** [comment]
Also, I found the full image here https://vignette.wikia.nocookie.net/steins-gate/images/d/d3/Faris_full_profile.png

**Comment by SaulMiquilena** [comment]
Done mate. Please review.

**Comment by yourWaifu** [comment]
I noticed a few issues stopping it from showing up on the site map and search, but I'll do it for you. Thank you for your time.

**Pull request merged**
