### PR TITLE
Added Oshino Shinobu

### PR DESCRIPTION
**Pull request by muazamkamal**

### CODE REVIEW

**Comment by yourWaifu** [comment]
I think you should add some appearance variables for this waifu. https://github.com/yourWaifu/is-your-waifu-legal/blob/master/reference.md#appearence-variables

**Comment by muazamkamal** [comment]
I'm not quite sure which appearance age I should put since her appearance can change, and it's not progressive throughout the show. Meaning at one point she might have an appearance of an adult, and further into the show she might change back to appearance of a kid.

Thoughts?

**Comment by yourWaifu** [comment]
You can add more the one note in notes, I think what you said is perfect for a 2nd note. To add a 2nd note, in the variable ``notes``, add a ``,`` after the ``"`` and then add another string.

**Comment by muazamkamal** [comment]
Done!

**Pull request merged**
